[workspace]
members = [
    "noops-cli",
    "noops-server",
    "component-rust"
]

[workspace.package]
authors = ["Giom-fm <giom@jfcomputing.io Falumpaset <marc@jfcomputing.io"]
[workspace.dependencies]


