[workspace]
members = [
    "noops-cli",
    "noops-server"
]

[workspace.package]
authors = ["Giom-fm <giom@jfcomputing.io Falumpaset <marc@jfcomputing.io"]
[workspace.dependencies]
anyhow = "1.0.69"


