application:
  name: "Hello-World"
  version: 0.0.1
  
secret_file: "./my-secrets.yaml"

functions:
  - function:
      name: "my-function"
      source: "src/my-function.rs"
      description: "my super duper function"
