default world handler {

    record request {
        params: list<tuple<string, string>>
    }

    record response {
        status: u32,
        body: string
    }

    export handle: func(req: request) -> response
}