// Generated by `wit-bindgen` 0.4.0. DO NOT EDIT!
#include "handler.h"


__attribute__((weak, export_name("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

// Helper Functions

void handler_list_string_free(handler_list_string_t *ptr) {
  for (size_t i = 0; i < ptr->len; i++) {
    handler_string_free(&ptr->ptr[i]);
  }
  if (ptr->len > 0) {
    free(ptr->ptr);
  }
}

void handler_request_free(handler_request_t *ptr) {
  handler_list_string_free(&ptr->headers);
  handler_list_string_free(&ptr->params);
}

void handler_string_set(handler_string_t *ret, const char*s) {
  ret->ptr = (char*) s;
  ret->len = strlen(s);
}

void handler_string_dup(handler_string_t *ret, const char*s) {
  ret->len = strlen(s);
  ret->ptr = cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void handler_string_free(handler_string_t *ret) {
  if (ret->len > 0) {
    free(ret->ptr);
  }
  ret->ptr = NULL;
  ret->len = 0;
}

// Component Adapters

__attribute__((export_name("handle")))
int32_t __wasm_export_handler_handle(int32_t arg, int32_t arg0, int32_t arg1, int32_t arg2) {
  handler_request_t arg3 = (handler_request_t) {
    (handler_list_string_t) { (handler_string_t*)(arg), (size_t)(arg0) },
    (handler_list_string_t) { (handler_string_t*)(arg1), (size_t)(arg2) },
  };
  handler_response_t ret;
  handler_handle(&arg3, &ret);
  return (int32_t) ((ret).status);
}

extern void __component_type_object_force_link_handler(void);
void __component_type_object_force_link_handler_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_handler();
}
