cargo-features = ["per-package-target"]

[package]
name = "return-status-code-200"
version = "0.1.0"
edition = "2021"
default-target = "wasm32-wasi"

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = "0.11.0"