name: Release
on:
  push:
    branches:
      - release

jobs:
  build-and-sign:
    name: build and sign release assets
    runs-on: ubuntu-latest
    permissions:
      # cosign uses the GitHub OIDC token
      id-token: write
      # needed to upload artifacts to a GH release
      contents: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install toolchain
        uses: dsherret/rust-toolchain-file@v1

      - name: build release
        run: "cargo build --release --bin noops"
  


  upload-to-release:
    needs: build-and-sign
    runs-on: ubuntu-latest
    steps:
      - name: Upload To Github Release
        uses: xresloader/upload-to-github-release@v1.3.12
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
        with: 
          file: target/release/noops
          draft: false
          tags: true

  